config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  resources :users, only: [:show, :index, :create, :edit, :update]
  resources :books, only: [:index, :create, :destroy, :edit, :show, :update]
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true,
                   length: { maximum: 200 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :move_to_signed_in
  def index
    @book = Book.new
    @books = Book.all
  end
  
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: 'You have created book successfully.'
    else
      @books = Book.all
      @book.user_id = current_user.id
      render :index
    end
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  
  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
    else
      render :edit
    end
  end
  
  def show
    @books = Book.new
    @book = Book.find(params[:id])
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end
  
  def move_to_signed_in
    unless user_signed_in?
      redirect_to  '/users/sign_in'
    end
  end
  
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_side.html.erb
<h1>User info</h1>
  <div>
    <%= image_tag user.get_profile_image(100,100) %>
    <p class="border-top">name:<%= user.name %></p>
    <p class="border-top">introduction:<%= user.introduction %>	</p>
  </div>
  
  <div class="col">
  <%= link_to edit_user_path(user) do %>
    <button style="button", class="btn-block"><i class="fas fa-user-cog"></i></i></button>
  <% end %>
  </div>
  
  <h2 class="mt-3">New book</h2>
    <%= form_with model: books, url:'/books' do |f| %>
  <p>Titel</p>
    <%= f.text_field :title %>
  <p>Body</p>
    <%= f.text_field :body %>
  
  <div class="col pt-3">
    <button style="background-color: limegreen ", class="text-white"><%= 'Create Book' %></button>
<% end %>
</div>

app/views/books/edit.html.erb
<div class= "container px-5 px-sm-0 mt-3" >
<% if @book.errors.any? %>
  <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
<ul>
  <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>
<% end %>
</div>


<div class="col-lg-5 mx-auto">

<h1>Editing Book</h1>

<%= form_with model: @book do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title, size: "40" %>
  
  <h4>Opinion</h4>
  <%= f.text_area :body, size: "50" %><br>
  
  <%= f.submit 'Update Book' %><br>
  
  <%= link_to 'Show', book_path(@book.id) %>
  <%= link_to 'Back', books_path %>
  
<% end %>
</div>

app/views/books/index.html.erb
<div class= "container px-5 px-sm-0 mt-3" >
<% if @book.errors.any? %>
  <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
<ul>
  <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>
<% end %>
</div>


<div class="container px-5 px-sm-0">
<div class="row pr-5">
<div class="col-md-3">
  <%= render 'side',  user: current_user, books: @book %>
</div>

<div class="col-md-8 offset-md-1">
<h1>Books</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <td></td>
      <td>Title</td>
      <td>Opinion</td>
    </tr>
  </thead>
  
  <tbody>
  <% @books.each do |book| %>
    <tr>
      <td><%= link_to image_tag(book.user.get_profile_image(100,100)), user_path(book.user_id) %></td>
      <td><%= link_to book.title, book_path(book.id) %></td>
      <td><%= book.body %></td>
    </tr>
  <% end %>
  </table>
</div>
</div>
</div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-3">
  <%= render 'side', bookd: @book.user, user: @book.user, books: @books %>
</div>

<div class="col-md-8 offset-md-1">
<h1>Book detail</h1>
<table class="table table-striped">
  
<%= form_with model: @book do |f| %>
<tbody>
  <tr>
    <td>
      <%= image_tag @book.user.get_profile_image(100,100) %>
      <div class="d-flex-block"><%= link_to @book.user.name, user_path(@book.user.id) %></div>
    </td>
    <td><%= @book.title %></td>
    <td><%= @book.body %></td>
    
    
     <% if @book.user == current_user %>
  　   <td>
  　     <%= link_to edit_book_path(@book.id) do %>
  　       <button style="background-color:limegreen ", class="text-white">Edit</button>
        <% end %>
  　   </td>
    <% end %>
    <% if @book.user == current_user %>
      <td>
        <%= link_to book_path(@book),  method: :delete do %>
          <button style="background-color: red ", class="text-white">Destroy</button>
        <% end %>
      </td>
    <% end %>
    
  </tr>
</tbody>
<% end %>
</table>
</div>
</div>
</div>