config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  resources :users, only: [:show, :index, :create, :edit, :update]
  resources :books, only: [:index, :create, :destroy, :edit, :show, :update]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://kit.fontawesome.com/85af9799b5.js" crossorigin="anonymous"></script>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
          <%= link_to root_path do %>
            <span class="text-light navbar-brand">Bookers</span>
          <% end %>
          
          <div>
          <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li>
              <%= link_to user_path(current_user.id) do %>
                  <div class="nav-link text-light">
                  <i class="fas fa-home"></i>
                  Home
                </div>
              <% end %>
            </li>
            <li>
              <%= link_to  users_path do %>
                <div class="nav-link text-light">
                  <i class="fas fa-users"></i>
                  Users
                </div>
              <% end %>
            </li>
            <li>
              <%= link_to  books_path do %>
                <div class="nav-link text-light">
                  <i class="fas fa-book-open"></i>
                  Books
                </div>
              <% end %>
            </li>
            <li>
              <%= link_to  destroy_user_session_path, method: :delete do %>
                <div class="nav-link text-light">
                  <i class="fas fa-sign-out-alt"></i>
                  Log out
                </div>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to root_path do %>
                <div class="nav-link text-light">
                  <i class="fas fa-home"></i>
                  Home
                </div>
              <% end %>
            </li>
            <li>
              <%= link_to home_about_path do %>
                <div class="nav-link text-light">
                  <i class="fas fa-link"></i>
                  About
                </div>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path do %>
                <div class="nav-link text-light">
                  <i class="fas fa-user-plus"></i>
                  Sign up
                </div>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path do %>
                <div class="nav-link text-light">
                  <i class="fas fa-sign-in-alt"></i>
                  Log in
                </div>
              <% end %>
            </li>
          <% end %>
          </ul>
          </div>
          
      </div>
    </header>
    <% flash.each do |key, value| %>
    　<%= content_tag(:div, value, class: "#{key}") %>
  　<% end %>
    <%= yield %>
  </body>
  <footer>
    <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
  </footer>
</html>